import { render } from "preact";
import { App } from "./app";
import "dockview-core/dist/styles/dockview.css";
import "./styles/dockview-overrides.css";
import "./styles/global.css";
import "./styles/topbar.css";
import "./styles/chart.css";
import "./styles/subway.css";
import "./styles/detail.css";
import "./styles/log.css";
import "./styles/api.css";
import "./styles/sandbox.css";
import "./styles/prompts.css";
import "./styles/suggest.css";
import "./styles/tags.css";
import "./styles/task.css";
import "./styles/stats.css";
import "./styles/chat.css";
import "./styles/table.css";

render(<App />, document.getElementById("app")!);
